;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
;	1DT301, Computer Technology I
;	Date: 2016 - 09 - 06
;	Author:
;		Martin Lyrå
;		Yinlong Yao
;
;	Lab number: 1
;	Title: How to use the PORTs. Digital input/output. Subroutine call.
;
;	Hardware: STK600, CPU ATmega2560
;
;	Function: Runs a Johnson Counter (similar to a stack; goes to top, then back down to square zero)
;	on all LEDs 0 to 7 via PORTB
;
;	Input ports: None
;
;	Output ports: PORTB
;
;	Subroutines: None
;
;	Included files: m2560def.inc
;
;	Other information:
;
;	Changes in program:
;		2017-09-04: File created
;
;<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

.include "m2560def.inc"

; Initialize stack pointer
ldi r16, low(RAMEND)
out SPL, r16
ldi r16, high(RAMEND)
out SPH, r16

ldi r16, 0xFF			; Set up PORTB as output
out DDRB, r16

; Main Routine
; r21 = Direction: 0 = increment, 1 = decrement
main:
	cpi r21, -0			; Are we in incrementing mode?
	breq increment		; If equal to 0 (all bits are zeros), go to increment label
	decrement:
		call shift_neg	; Call shift_neg subroutine
		cpi r20, -0		; Are all leds turned on (all bits are '0's)?
		brne endif		; Break the "if statement" if not
		ldi r21, -0		; If all leds are turned on, switch to increment mode
		jmp endif
	increment:
		call shift_pos	; Call shift_pos subroutine
		cpi r20, -1		; Are all leds turned off (all bits are '1's)?
		brne endif		; Break the "if statement" if not
		ldi r21, -1		; If all leds are turned off, switch to decrement mode
	endif:				; End if
	out PORTB, r20		; Push the new state to PORTB
	call delay			; Call delay subroutine
rjmp main

; Shifts all bits in r20 to left with one step, then adds one at right end by incrementing
; the register.
shift_pos:
	lsl r20
	inc r20
ret

; Makes the LSB (the right-most bit) a zero, then shifts all bits 
; in r20 to right with one step. Reverse function of shift_pos
shift_neg:
	dec r20
	lsr r20
ret

; Delay subroutine
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; Modified post-generation, settings unavailable
; Delay approx. between 0,2 - 0,4 seconds
delay:

	ldi r17, 2
	ldi r18, 2
	ldi r19, 2

	L1: 
	dec r19
	brne L1
	dec r18
	brne L1
	dec r17
	brne L1
	nop

ret
